### ISSUE TITLE
BUG: Review + fix the use of "comment" vs "argument"

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-api#116]
In the old days, arguments were named "comments". Since then, we've decided to split and separate the two, both ideologically and hierarchically: 
- Argument is the pro or con statement you can leave under a topic
- Comment is a reply you can leave to the argument, placed lower in the hierarchy.

However, in the API, emails still talk about comments, while they probably have arguments in mind.
Please review and fix "comment" => "argument" where applicable and necessary.

**Comment by anettlinno** [comment]
Triage 58. Needs the review in API and change "comments" to "arguments". 
Est. dev. time 30 minutes. Sending to development.

**Comment by ilmartyrk** [comment]
@oksks I've updated the e-mails and replaced comments with arguments in source.json and main templates
