### ISSUE TITLE
Database SQL not updated after new migration?

### ISSUE THREAD

**Issue by moll** [citizenos/citizenos-api#121]
Something seems off. https://github.com/citizenos/citizenos-api/blob/master/db/config/database.sql lists a single migration at the end of the file, yet https://github.com/citizenos/citizenos-api/tree/master/db/migrations lists two migrations.

Did someone forget to update the .sql file when adding a migration?

**Comment by tiblu** [comment]
@moll Thanks, updated!

**Comment by tiblu** [comment]
Also, to throw it out here, we have Wiki on how DB migrations work and developers should dev/test - https://github.com/citizenos/citizenos-api/wiki/DB-Migrations
