### ISSUE TITLE
Signing people in with email verification is risky

### ISSUE THREAD

**Issue by moll** [citizenos/citizenos-api#122]
I think I noticed the email verification link signs you in. Is that correct? That's a relatively risky approach given that if I make a mistake with my email address, for example, and you get to click that link before I manage to correct my email address, you'll presumably have a session to my account that I'm then unaware of and currently cannot revoke in any way. Better have the link _only_ confirm the email address and nothing more.

**Comment by tiblu** [comment]
Notes on Citizen OS behavior:

* When User clicks verify in the e-mail after registration, User is sent to Citizen OS App `/home`. Should we take to login instead?
* When User click verify in the e-mail after changing e-mail in the profile, User is sent to Citizen OS App `/home`. Should we take to login instead?

**Comment by tiblu** [comment]
Done.

**Comment by moll** [comment]
What's done? :P It's not signing in any longer?

**Comment by tiblu** [comment]
Yes, not signing in.

**Comment by moll** [comment]
Great!

**Comment by KatiVellak** [comment]
As this is corrected and user is directed to signing in (not being signed in) after email address verification, no further legal comments.
