### ISSUE TITLE
API: Upgrade FB API 2.8 -> 3.2 before 18th of April 2019

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#126]
**Overview**

2.8 version of FB API will be shut down 18th of April 2019.

Changelog: https://developers.facebook.com/docs/graph-api/changelog

**TODO**

- [ ] Upgrade to FB API version >=3.1

**Comment by tiblu** [comment]
Upgraded passport-facebook to 3.0.0

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
