### ISSUE TITLE
NPM shrinkwrap

### ISSUE THREAD

**Issue by moll** [citizenos/citizenos-api#13]
Hey,

For both security _and_ reproducible installations, please add a `npm-shrinkwrap.json` file with known-to-be-working dependency versions (generate it with `npm shrinkwrap`). Having versions in package.json is insufficient as nested dependencies still get upgraded. Having versions in `package.json` given `npm-shrinkwrap.json` is then redundant and unnecessary.

**Comment by tiblu** [comment]
**Notes on shrinkwrap**

* `package.json` versions are irrelevant, the versions to be installed are described in `npm-shrinkwrap.json`
* Always install/update/remove dependencies with NPM cli commands, this keeps dependencies in check.
* After modifying dependencies, new `npm-shrinkwrap.json` needs to be generated using `npm shrinkwrap`
     * **WARNING:** `npm-shrinkwrap.json` file is generated based on the current structure of `node_modules` directory. That means - if you experiment, don't forget to remove these as they will be added to `npm-shrinkwrap.json`

**Comment by tiblu** [comment]
@ilmartyrk We're going use shrinkwrap for all of our Node projects. If we touch any of our Citizen OS projects, let's add shrinkwrap. The etherpad-lite-heroku may be a tricky one, but for the rest it should be quite straightforward.  

For further reading see comment https://github.com/citizenos/citizenos-api/issues/13#issuecomment-441368944
