### ISSUE TITLE
API: Topic content sync with Etherpad is slow and causes Etherpad performance to drop significantly

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#131]
Related issues:

* https://github.com/ether/etherpad-lite/issues/3589
* https://github.com/citizenos/citizenos-fe/issues/205

**Comment by tiblu** [comment]
### Why the sync?

1. Loading Etherpad for every view is very slow, even in read-only mode, so when implementing the editor, we decided to load the Etherpad only when in "edit" mode to provide better user experience, specially with slow connections.
2. There are views, where the full document is not shown, but parts of it - only the title for example.
3. Etherpad is a separate application with it's own database and server. We want to keep the loose coupling and not touch Etherpad internals from Citizen OS code directly.


### The current sync

After code review , @ilmartyrk found that  Citizen OS API does the sync with revision number, which causes the Etherpad (EP) API to fall into expensive revision fetch and apply logic. We're changing it to call it without revision, which falls into much cheaper logic on the Etherpad side.


### Future of the sync?

* We MAY want to contribute to making Etherpad read-only view loading faster, because in the future the read-only view of the Topic should show all the inline comments and inline votes etc which all are integrated into Etherpad. Sync becomes less important if we load the full EP read-only view with latest info from EP database.
* The sync MAY still remain, because we have less places and less info to show in the views that do not show the full document. Mostly we only need the title for the dashboard, `/home` still uses the full document text tho, but if that is a bit out of sync, that's not a big deal.
* When we start having performance issues with the sync, we will increase the `ep_webhook` debounce parameter thus syncing with a bigger interval. While the read-only views will be a bit out of date, it goes a long way in terms of performance gains.

**Comment by tiblu** [comment]
@ilmartyrk Discovered that our EP to Citizen OS DB sync does call to Etherpad API with revision number, which makes EP to fall into expensive logic. @ilmartyrk Changed it to use API without revision numbers, which is ALOT cheaper.

**Comment by tiblu** [comment]
Closing this issue, but we do need to have a discussion on the future - https://github.com/citizenos/citizenos-api/issues/131#issuecomment-481720616

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
> Closing this issue, but we do need to have a discussion on the future - [#131 (comment)](https://github.com/citizenos/citizenos-api/issues/131#issuecomment-481720616)

Apparently, this got fixed with Etherpad 1.8. So no longer an issue for the future. Issue fully closed and done.
