### ISSUE TITLE
LEGAL:  Store User IP

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#133]
We have to connect every inserted text with IP so it could be given out if necessary. 
There are different ways to do so. 
a) We alter all data tables with IP fields and add IP with every insertion
b) We alter Users with IP and update on every login or status check if IP changes
c) We create new sessions table where we store session info: userId, IP

**Comment by ilmartyrk** [comment]
Going to choose option a)

**Comment by tiblu** [comment]
@ilmartyrk What if we stored the IP with an Activity instead?
Every data modification does create an activity?
This solution would save us from modifying every table, but just adding IP to stored Activity-s JSON or table structure?

**Comment by ilmartyrk** [comment]
@tiblu, jep that sounds even more logical. Will check for any possible failure points and if everything is OK will only alter Activities table

**Comment by KatiVellak** [comment]
Legally reviewed, during the discussions legal input provided.
