### ISSUE TITLE
Vote signing: Smart ID

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#134]
~BLOCKED: SmartID has not been approved as an method of digital signing.~
Smart ID has been approved as valid signing method.

**Comment by ilmartyrk** [comment]
Smart-ID signing is quite easy to implement, but there seems to be an issue with getting signed container. 
Possible solutions:
a) Check Smart-ID documentation if there is something to hint why signed container is not returned
b) Contact customer support, maybe they have any ideas
c) Implement [digidoc4j ](https://github.com/open-eid/digidoc4j) with [digidoc4j-smart-id-adapter](https://github.com/SK-EID/digidoc4j-smart-id-adapter) to add signatures and create containers in API

**Comment by ilmartyrk** [comment]
SK ID Solutions AS DigiDocService specification
NB! DigiDocService will be replaced by new Mobile-ID REST API during 2019/2020.

Especially when doing new developments please use new REST API! Starting from June 2019 new customers are only allowed to use Mobile-ID REST API and will no longer granted an access to DigiDocService.

Mobile-ID REST API specification you can find here: https://github.com/SK-EID/MID/wiki

So we should probably start implementing new digidoc signing interface where we create bdoc locally and add signatures locally as we need to with smart-id or we should find a new service for it

**Comment by loorm** [comment]
Triage 16. @ilmartyrk - have you also solved this issue while solving #134?

**Comment by loorm** [comment]
Tested on laptop and Android phone + tablet. Confirmed working.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
