### ISSUE TITLE
Permit configuring JWT with symmetric key

### ISSUE THREAD

**Issue by moll** [citizenos/citizenos-api#14]
Using public and private keys for JWT is a bit overkill right now. One could just configure JWT to use symmetric methods, but `app.js` explicitly prevents that through https://github.com/citizenos/citizenos-api/blob/master/app.js#L205. I propose that limitation be removed.

**Comment by anettlinno** [comment]
Triage 37. Closing this issue with opportunity to develop this functionality for users who need this.
