### ISSUE TITLE
(Topic report) Confusing info in an email

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-api#140]
**What is the problem?**
1) The email leaves an impression, that the moderator has written an explanation for the report. 

![Screenshot 2019-07-03 at 14 05 09](https://user-images.githubusercontent.com/34126353/60587065-31f35380-9d9c-11e9-9331-416bd217b182.png)

2) The whole topic report emails' structure (or lack thereof) is confusing, overall.. There's too much text and it's not well structured - as a user, I want to understand at a glance, what it is I'm being asked to do, otherwise it's too much hassle to read into all that.

Maybe invite Kevin over for a UX review, now that we have the emails with actual email content? 

I also think it might make sense to swap the placement of two information fields as follows:

![Screenshot 2019-07-03 at 16 46 32](https://user-images.githubusercontent.com/34126353/60596666-2579f580-9db2-11e9-95db-665eef98ae4d.png)

**Comment by loorm** [comment]
Triage #8: reclassified the report from BUG to UX. This is not a bug, since the text of the e-mail right now is by design. We will review the design, once Mikk is back from summer mode.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Let's do this:
- re-arrange the blocks 1-2-3 within e-mail, as proposed
- change string "Your explanation" in details of the report to simply "Explanation"

Leave everthing else as is. This is not an e-mail to a regular user, it is an e-mail to a moderator. This requires a slightly higher ability to concentrate on verbal information.

Ready for development.

**Comment by ilmartyrk** [comment]
@loorm  @oksks I'll have to add that there are actually 3 different emails with the same layout logic, 1. For all topic members 2. For moderators (as is the current example in this issue) 3. The person who reported the topic. I'll update all layouts, but it might still need further UX improvements at least for topic members

**Comment by loorm** [comment]
Tested. Confirmed working. Is more logical even for a topic member.
