### ISSUE TITLE
INVESTIGATE: How does Heroku encrypt our DB and it's backup copy?

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-api#149]
From Triage 13, "7. Critical data encryption in DB?"

**Comment by tiblu** [comment]
https://devcenter.heroku.com/articles/heroku-postgres-production-tier-technical-characterization#data-encryption

> Data encryption
All production plans (Standard, Premium, Private and Shield) are encrypted at rest with AES-256, block-level storage encryption. Keys are managed by Amazon, and individual volume keys are stable for the lifetime of the volume. You can find more detail about EBS encryption here. Heroku does not encrypt anything for you at the Postgres level, so if you wish to do this, you can use the PGCrypto extension for your own encryption.

> All backup files that are taken using Heroku PGBackups are stored in an encrypted S3 bucket in the US region.

In conclusion:

* All DB data is encrypted at rest, that is data is encrypted when it stored. All stored data is encrypted. DBs are actually hosted in AWS.
* All backups are encrypted also.
* I don't see the need for extra encryption.

Safety:

* Require 2FA authentication from all Heroku users that have access to apps and their conf.
* SSH key based access from Heroku CLI

Resources:

* https://docs.aws.amazon.com/whitepapers/latest/efs-encrypted-file-systems/encryption-of-data-at-rest.html
* https://docs.microsoft.com/en-us/azure/security/fundamentals/encryption-atrest
* https://devcenter.heroku.com/articles/heroku-postgres-production-tier-technical-characterization#data-encryption
*

**Comment by loorm** [comment]
Thank you for investigating, @tiblu! Happy with the answer. Do we need to copy any part of this answer into some more permanent project documentation file here on Github or elsewhere?

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
