### ISSUE TITLE
Smart-ID certificate renewal (4th of December 2019 15:30) - validate systems

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#153]
**What?**

Smart-ID certificate will expire and needs to be updated **by 4 th of December 2019 15:30**

New certificates:

* DER - https://www.sk.ee/upload/files/rp-api_smart-id_com_2019.DER.crt
* PEM - https://www.sk.ee/upload/files/rp-api_smart-id_com_2019.PEM.crt

> Tere,
> 
> Seoses Smart-ID teenuse (RP-API) TLS/SSL sertifikaadi aegumisega võtab SK ID Solutions antud teenuses 4. detsembril 2019 kell 15:30 kasutusele uue sertifikaadi.
> 
> Muudatus mõjutab kõiki Smart-ID toega teenused ehk neid, kus võimaldatakse Smart-ID-ga autentimist või allkirjastamist.
> 
> Palume kindlasti õigeaegselt muuta RP-API sertifikaat! Kui e-teenuse omanik ei muuda RP-API sertifikaati, ei ole e-teenuse kasutamine Smart-ID-ga võimalik.
> 
> NB! Uus teenussertifikaat on välja antud senisest erineva sertifitseerija alt, milleks on DigiCert SHA2 Secure Server CA
> 
> Uue e-teenuse liidese sertifikaadi saab alla laadida siit: DER, PEM
> 
> Kui teil tekkis küsimusi, siis palun kirjutage e-posti aadressil support[A]sk.ee.
> 
> SK ID Solutions AS
> +372 610 1880
> 
>  --------
> 
> Change of Smart-ID interface certificate
> 
> Hello, 
> 
> As the TLS/SSL certificate of the Smart-ID service interface (RP-API) will expire, we will apply a new certificate on 04.12.2019 at 15:30.
> This change will impact all e-services that have integrated Smart-ID for authentication and signing.
> 
> Please ensure that the certificate is changed in a timely manner as e-service providers who have not done so will not be able to use Smart-ID for authentication and signing in their e-service.
> 
> NB! The issuer of the new certificate will be DigiCert SHA2 Secure Server CA
> 
> The new certificate can be downloaded at: DER, PEM
> 
> If you have any questions regarding this change, please contact us at support[A]sk.ee.
> 
> SK ID Solutions AS
> +372 610 1880
> 
>

**Comment by tiblu** [comment]
If I get it correct, SK is changing server certificate for https://rp-api.smart-id.com to a one that is issued by DigiCert. As we trust DigiCert as a CA, we should not have to do anything.

**Comment by tiblu** [comment]
Verified:

* Certificate of https://rp-api.smart-id.com/ has been updated.
* Citizen OS authentication still works.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
