### ISSUE TITLE
ID-card signing/auth without proxy server

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#157]
**Overview**

By the information from @moll we have a possibility to get rid of the client-server authentication solution for ID-card signing/auth.

Src:

* https://github.com/rahvaalgatus/rahvaalgatus/blob/master/views/sessions/create_page.jsx#L101

**TODO:**

- [x] Implement similar solution to Rahvaalgatus - https://github.com/rahvaalgatus/rahvaalgatus/blob/master/views/sessions/create_page.jsx#L101

**Comment by loorm** [comment]
Triage 17. 2 developer days estimated. Not urgently needed, but would simplify our process and installation of instances.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
