### ISSUE TITLE
Email layout is wonky on mobile

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-api#159]
**What is the problem?**
While our transactional emails look fine on desktops, on a mobile, the design is off - texts are smooshed together, alignment is thrown off, too much blank space in places, etc.

**Here's a screenshot of an email on desktop computer:**

<img width="624" alt="Screenshot 2020-02-10 at 10 00 39" src="https://user-images.githubusercontent.com/34126353/74131463-07e4f800-4bed-11ea-9935-d5f4e142439a.png">

**And here's how the same email looks on a mobile:**

![Screenshot_20200206-170718_Gmail](https://user-images.githubusercontent.com/34126353/74131412-ebe15680-4bec-11ea-8b91-427c49779309.jpg)

**Why is this a problem?**
It looks unprofessional.

**Possible solution.**
Layout should be responsive to various screen sizes.

**Comment by loorm** [comment]
Triage 18: @kevincrepin Do you have input on this or do you just want developers to hack something (like reduce the font size)?

**Comment by kevincrepin** [comment]
Should look more like this: 
![mail_mobile](https://user-images.githubusercontent.com/26792281/75340569-67086500-589b-11ea-8dd1-d47b6442d540.png)

But we once made new e-mail templates: https://projects.invisionapp.com/d/main#/console/9829159/404593154/preview

We should use the same ones everywhere.

**Comment by ilmartyrk** [comment]
@kevincrepin @loorm, I am unable to replicate the original issue, but do I understand correctly that the layout should still get a revisit? If I do then what solution is correct? Image in here by  @kevincrepin  or image behind the link in invision?

**Comment by oksks** [comment]
To specify - I'm using Samsung Galaxy S9 and Chrome. Adding a fresh screenshot I just made.

![Screenshot_20200402-150832_Gmail](https://user-images.githubusercontent.com/34126353/78247685-f8e73b80-74f3-11ea-9932-1e92c541dcbf.jpg)

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by loorm** [comment]
Tested. Confirmed working on Galaxy S7 and Gmail app.
