### ISSUE TITLE
API POST /api/auth/id - rewrite the code so that it's less likely to accidentially trust certificate when not supposed to

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#16]
As per comments - https://github.com/citizenos/citizenos-api/commit/7b95c9e3bf790bcd2903cd2d3b49fc8573ed375b#diff-d12ae772f9826d4096efd4221a1874c9R572

**Comment by anettlinno** [comment]
Triage 37. Seems that this is not an issue any more, but needs some investigation. 
Investigation time 30 minutes. Sending to to do.
