### ISSUE TITLE
Optimize (speed up) activity feed

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-api#161]
**What is the problem?**
This is the problem: https://youtu.be/-r-EIg4H0ps

**Why is this a problem?**
Response to user action in <= 1 sec
0.2 sec gives the felling of instantaneous response
1.0 second is about the limit for user's flow of thought to stay uninterrupted, even though the user will notice the delay. Normally, no special feedback is necessary for delays < 1 sec, but the user does lose the feeling of operating directly with the System.
Source: https://github.com/Tendrl/documentation/wiki/Best-Practices-for-Response-Times-and-Latency

**Possible solution.**
N/A

**Comment by loorm** [comment]
Triage 17: give this high priority, because current response times are a constant pain to all users.

**Comment by ilmartyrk** [comment]
FIxed by https://github.com/citizenos/citizenos-api/commit/b3ef28c0b21179640bcea133bf04e051817502ef

**Comment by loorm** [comment]
Tested. Confirmed working. Load time ca 1 second.

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
