### ISSUE TITLE
Possibly drop login check from vote signing process

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#162]
**What is the problem?**
When user has multiple accounts, for example 1 for private use and one with work e-mail. User now cannot sign votes for one account because users personal id can only be linked to one account.

**Why is this a problem?**
This is a problem because possible solutions are that user must be added to topic with two accounts possibly mixing work and private things etc.

**Possible solution.**
Drop login check from signing process, this might include removing userinfo file from container or just using the userId that user is logged in while signing. Other possible solution is to allow multiple user connections with same values, this would need a new login view where user can choose between accounts to use when logging in.

**Comment by ilmartyrk** [comment]
We should also start marking user accounts somehow if they have verified (has connection with smart-ID, Mobiil-ID etc.) or not verified (email) accounts.

**Comment by tiblu** [comment]
## Possible solutions

### 1. Do not check that logged in User is the same that has the PID connected to his/her account when sigining.

Remove `userId` check against `userConnection` PID (Personal Identification number / ET: isikukood). The vote would be tied to the User that is currently logged in.

#### Pros

* No confusion with accounts, User can sign a Vote with whatever account they are logged in with.
* Technically quick and simple solution, basically removal of one check.

####  Cons

* Vote counting will be off IF User signs a Vote with different accounts. Vote counting needs tuning.
* Causes confusion - when User logs in with Google and signs with Smart-ID. When User now logs in with Smart-ID, he/she will not see the Vote or the Topic IF the invite was sent for a Google account.

**Comment by ilmartyrk** [comment]
## Current task list

- [ ] Remove user connection check from vote signing process
- [ ] Update all user connections with PID to have PNO{countryCode} prefix
- [ ] Fix final container

**Comment by tiblu** [comment]
@loorm Has approved solution 1 (https://github.com/citizenos/citizenos-api/issues/162#issuecomment-588160165) as a temporary solution.
@ilmartyrk Is implementing it.

We need to restart discussions on the accounts and connections again. Seems the UX needs to change, there is a lot of problems around different accounts and signing.

**Comment by ilmartyrk** [comment]
Created DB backup with name b1508

**Comment by ilmartyrk** [comment]
@loorm, @tiblu Updated `"UserConnections" "connectionUserId"` to have"PNO{country}-"prefix where `connectionId `is `esteid `or `smartid`. Updated final.bdoc csv to no have possible duplicate values [with commit](https://github.com/citizenos/citizenos-api/commit/9746641e4bca89504aab82ab794fdf0864ede264).
While vote count in the UI could possibly still be false, final container is now with valid values

**Comment by loorm** [comment]
Triage 18: no acute issue, fix works. But a larger discussion / user story is needed.

**Comment by loorm** [comment]
I think by making changes to invites, login flows etc, we have now solved all these multiple account-related issues. The fix above also works. There's nothing further to do under this issue. Moving to Triage and proposing to close the issue.
