### ISSUE TITLE
Invalid vote container for hard-auth

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#163]
**Reproduce**

![image](https://user-images.githubusercontent.com/7405383/75250159-65c63200-57e0-11ea-8720-893080048431.png)

* Create a Topic
* Create custom vote
* Add options that are on the screenshot.
* Send to Voting
* Vote with hard-id (Mobiil-ID, ID-kaart, Smart-Id)
* Download your vote container

**Result**

* User can download the BDOC, but the BDOC is invalid.
    * BDOC client error ![image](https://user-images.githubusercontent.com/7405383/75250260-a756dd00-57e0-11ea-924b-8d4bf0228018.png)
    * 7zip client error ![image](https://user-images.githubusercontent.com/7405383/75250292-b76ebc80-57e0-11ea-8f31-f769eb48059e.png)

**Expected**

* Downloaded BDOC is valid by DigiDoc Client and 7z

**Comment by ilmartyrk** [comment]
Quick test shows that containers are broken, if vote is with custom options and options contains õäöü etc.

**Comment by ilmartyrk** [comment]
Solution, as all option files contain option id and value, change filename in in user container from `{optionValue}.html` to `"option.html" `or `"chosen_option"`. In final container replace filenames to include index `option_1.html, option_2.html`

**Comment by loorm** [comment]
Assign critical, because a part of core functionality is down. Criteria "App not usable" fulfilled. Divert dev resources to solving this issue.

**Comment by ilmartyrk** [comment]
@loorm, I am on it

**Comment by ilmartyrk** [comment]
Traced the issue back to `js-undersign` that we use to make bdoc containers. Forked js-undersign, fixed the issue and created a pull request, replaced path in package.json to refere to our fork with fix. Issue is fixed for future, still we'll have to check if any containers in database are broken https://github.com/citizenos/citizenos-api/commit/63fae3817b1e10104b56ced5fadbdce5a3d981a0
