### ISSUE TITLE
Authenticate via Okta

### ISSUE THREAD

**Issue by ottomattas** [citizenos/citizenos-api#165]
**Overview**
We are introducing CitizenOS within our company. The company has made a strategic decision towards having only one account for it's employees to simplify identity and access management, namely an Okta account.

**Opportunity**
- CitizenOS is already using [PassportJS](http://www.passportjs.org/) for third party integrations for authentication:
https://github.com/citizenos/citizenos-api/blob/de48e39076055234c7242fe964fb8aa3a92b9fc9/libs/passport/index.js#L4
- [PassportJS](http://www.passportjs.org/) seems to be already supporting Okta with this method: http://www.passportjs.org/packages/passport-okta-oauth/

**Comment by loorm** [comment]
Triage 20 - we recognize opportunity and support this development. 2 further questions for @ottomattas:
1)  How widespread is Okta use?
2) What is your willingness to work on this development yourself with our support?

**Comment by ottomattas** [comment]
@loorm, I have gathered some insight to share with you:
1. Okta is a widely adopted enterprise solution. Many companies use it, for more details check their [list of customer success stories](https://www.okta.com/customers/?region=emea). Internally, we are using the solution for all of our employees, so about 600 users right now.
Okta has shown growth for the past years and I have a feeling this trend will continue. They provide a great complete service while it might be focused on enterprise customers. So overall, I think Okta is widespread and quite popular but I am looking from my "enterprise" perspective.
2. I am willing to work on this, absolutely. In order to prove the worth of this action, we need to see the [multi-choice voting](https://github.com/citizenos/citizenos-fe/issues/413) available. This will unlock a necessary feature for us so we can start using the platform. After we have gained traction and the business agrees with the benefit CitizenOS brings, I can dedicate myself here and work on the Okta integration.

**Comment by loorm** [comment]
@ottomattas Triage 21. Thank you for responding! We have seen and understood. We continue to work on multiple-choice as a high priority development.

**Comment by KatiVellak** [comment]
Legally reviewed, no further comments.

**Comment by loorm** [comment]
@ottomattas We have had multiple choice voting for some time now. Have you found it useful? Are you interested in proceeding with Okta development?

**Comment by ottomattas** [comment]
@loorm Unfortunately, I have not used the multiple choice voting option as I left my previous company that could have benefitted from this.

As for developing the Okta integration - this is currently in a completely different realm than I am. That said, I still think the feature might be interesting for enterprise customers as it could foster easy adoption and seamless integration with CitizenOS.

I will close the issue as the need went away. Thanks again for taking an active role in the discussions and looking for opportunities to collaborate. I have a feeling that we will see each other again in the future.
