### ISSUE TITLE
Update docx generating

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#178]
Docx generating library as been updated quite a lot since we last made any changes into our code.  I believe we should try and update our code.
1) We need to update the library, if possible drop our fork and use original release
2) Update html to docx code, probably should use async await to make it more readable

**Comment by loorm** [comment]
Triage 26. Discussed possibility to add PDF exports and custom Citizen OS features like mini-votes. Decided to keep the issue at it's current scope. Estimated dev time 2 days. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
