### ISSUE TITLE
Multiple choice, when Veto or Neutral override min/max options

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#179]
**What is the problem?**
When in multiple-choice voting and Vote has Veto and Neutral options enabled it should override Min/Max required selections

**Why is this a problem?**
Veto and Neutral are basically Opt-out options in a voting so they should not go under Vote min/max required selections count.

**Possible solution.**
Disable multiple options when user has selected Veto or Neutral in voting

**Comment by loorm** [comment]
Triage 26. Estimated dev time 4 hours. Prioritizing.

**Comment by KatiVellak** [comment]
Legally reviewed, no additions.
