### ISSUE TITLE
Vote creator can see who has voted in the middle of voting (hack)

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#182]
**What is the problem?**
When an admin closes (changes status to Follow up or closes the topic) the vote during voting and reopens the voting. He/she can download the final container and see who has voted and how and after that voting resumes where it was closed with all signatures remaining as were.
**Why is this a problem?**
It can lead to vote creator/admins to possibly start pushing users towards their own agenda and change the final outcome of the vote.

**Possible solution.**

1. Leave as is, creating a chance for re-opening voting if it was closed too early etc. 
2. Start new voting if a closed voting is reopened

**Comment by loorm** [comment]
Triage 28. This is a relevant issue. We would not consider it best practice, if during national elections, someone would close the vote, review results and then reopen voting :S :D 

Will not prioritize yet, let's get some more input. Scheduling for Triage 29.

**Comment by liinaguiter** [comment]
Good question. I hear from customer support, that this hack is used quite a bit. So @anettlinno 's input is important - to consider the user's viewpoint. I think it should be possible to re-open an ended voting. 

But also, it should not be possible to see the results until all voting on that topic has finished. Or if a user needs to see how many people have voted so far, it should be an anonymous count and not see how they voted. 

BTW, it only works when sending to 'follow up', if you 'close topic', then button 'send to voting' does not appear anymore.

**Comment by loorm** [comment]
We need to add a user story for creating public votes as oposed to private votes. This is how it is solved in the offline world. National elections are private. Noone will know, who voted or how. In-room board meetings are often public votes - everyone just raises their hand. This needs to be replicated on Citizen OS. Currently, we only have private voting and then some hacks to make it a little bit public for the vote creator.

**Comment by loorm** [comment]
Added "public voting" to User Epic 6 - Advanced voting procedures.
