### ISSUE TITLE
Mini-voting dialog box is displayed only once

### ISSUE THREAD

**Issue by loorm** [citizenos/citizenos-api#194]
**What is the problem?**
I go to topic editing. I click on mini-voting icon. The dialog box opens as it should.
I close the dialog box. Then, try to reopen it. No joy. Tried clicking anywhere on and around the green icon on the right. Tried clicking on the votable text. Nothing. Only if I close topic editing, then reopen topic editing, do I get the mini-voting dialog window to appear again.

**Why is this a problem?**
Long and uncomfortable to close, then reopen the topic every tim you want to see a voting dialog window.

**Possible solution.**
N/A

**Comment by loorm** [comment]
Triage 34. Replicated. Needs investigation. No hypothesis at this time. Estimated dev time 1 day.

**Comment by ilmartyrk** [comment]
FIXED https://github.com/citizenos/ep_inline_voting/commit/13820d261079c8dc7eed36438c4a75f9157d9ef6
