### ISSUE TITLE
Don't limit Topic title to 100 chars

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#2]
Parse and store whole title, let client decide what to do.

Related tasks:
* https://github.com/rahvaalgatus/rahvaalgatus/issues/58

**TODO**

- [x] Rise the limit 1000 chars in the DB and in the API code make the limit of title configurable.
- [x] Fix the character counting code so that it counts characters not bytes - https://app.citizenos.com/en/topics/f8f8bea2-362c-46c1-bae5-9d3bf8a83300

**Comment by moll** [comment]
Would still like this implemented. :)

**Comment by tiblu** [comment]
@moll Added to the project with a promising name. The thing is, the wish-list will go through review an prioritization at some point upcoming weeks we'll prioritize these and start crunching on the list. 

You can always pull request a fix if in a pinch. This issue MAY require some work in Citizen OS FE.

More - if you have some issues that have annoyed you for extended period of time, please add them to Winter Push For Perfection (WPFP) project. I cannot guarantee delivery in that project, but I can guarantee that we will go through them with the project, prioritize them and give feedback on why and where they stand in the list of work.

**Comment by moll** [comment]
ACK on fixing it myself. I'll ask @infokujur once we've got our instance set up.

Btw, I don't have permissions to move issues to projects.

**Comment by tiblu** [comment]
@moll OK, I'll review the project permissions and let's fix. Discussion move to Slack.

**Comment by tiblu** [comment]
@moll Remind me what was your proposal on this?

* Was it to remove the limit and allow whatever length?
* Was it to increase the limit?

**Comment by moll** [comment]
For all practical purposes, remove the limit. For practical purposes, bump it up to either half or a full thousand to prevent it accidentally including the body entirely.

**Comment by tiblu** [comment]
@moll We, me and @loorm, had a discussion on the limit. We would like to keep some kind of a limit. 
Reasoning being that we need a way to refer to a Topic in a human readable manner in several different places - activity feed, e-mails, topic list on the dashboard etc. 
IF we remove the limit, there is no incentive for a person to think of a title, that would be short and descriptive. 

What are the practical issues you're having because of the limit?

**Comment by tiblu** [comment]
It's been a while, this is what we decided to do after discussion with @ilmartyrk and @loorm:

* In this tasks scope:
    * Rise the limit 1000 chars in the DB and in the API code make the limit of title configurable.
* Show a warning to the User about the limit in the Etherpad while editing content - https://github.com/citizenos/citizenos-fe/issues/177
