### ISSUE TITLE
.BDOC not uploading as attachment

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#200]
We have a list of filetypes that users are allowed to upload as attachments, but seems that .bdoc upload is not working. Not sure why is it failing, is it an issue with server-side verification or S3 is rejecting it for some reason.

**Comment by loorm** [comment]
Triage 36. Replicated for bdoc, ddoc and asice files. bdoc and ddoc also give a cryptic "Object:object" error message. Need to allow uploads for all three types. 
Estimated time 16 hours. Prioritizing.

**Comment by tiblu** [comment]
Good idea to fix with - https://github.com/citizenos/citizenos-fe/issues/695

**Comment by ilmartyrk** [comment]
Fixed with https://github.com/citizenos/citizenos-api/commit/1e571d975b80ecb7498ecd0a80d1cbe591e11075
