### ISSUE TITLE
TECHNICAL DEPT: Add cascade on delete to related tables, where missing 

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#204]
When deleting "Topics" Groups etc. CASCADE should be added to all related models. Some new options have it missing thus when deleting from test or local database there are extra steps needed this shouldn't be an issue for our live setup as we avoid deleting anything where possible, but it could possible become an issue in the future.

**Comment by loorm** [comment]
Triage 37. Estimated dev time 4 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
FIXED by https://github.com/citizenos/citizenos-api/commit/bcf5425f0833883cb9658415254073a6e7b59398
