### ISSUE TITLE
Weird error message when trying to send topic from follow up back to voting

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#209]
When topic is sent to follow-up it currently should still be possible to send it back to voting, but it seems that when 2 users have voted on the topic it cannot be done as it falls into RAA related sent  to parliament logic.

To replicate: 
1) Create topic, create voting with requiring hard authentication
2) Get at least 2 users to cast their votes
3) Send topic to follow-up
4) Try to re-open voting

**Comment by loorm** [comment]
Triage 40. Estimated dev time 6 hours. Prioritizing.

**Comment by ilmartyrk** [comment]
This issue was caused because winning vote option contained value in string format and while hardcoded into config files the parameter was in integer format and that didn't cause any issues, but inserting the CITIZENOS_FEATURES_SENDTOPARLIAMENT_VOTECOUNTMIN value using environment variables it was also stored in string format.  This meant that comparison automatically started comparing alphabetically and that failed the whole if logic.
