### ISSUE TITLE
[SECURITY] Session Not Invalidated After Logout

### ISSUE THREAD

**Issue by EgidioRomano** [citizenos/citizenos-api#220]
**What is the problem?**
The application fails to properly invalidate the session cookie when users logout from Citizen OS. As such, the session cookie (JWT which is valid for many years, by default) could be used also when the user has logged out from the application - think about an [XSS](https://en.wikipedia.org/wiki/Cross-site_scripting) attack or another scenario, like an Internet Cafè, where the attacker does manage to steal the session cookie of a victim user, they can still impersonate a victim user even though they logout from Citizen OS.

**Possible solution.**
It is suggested to properly invalidate the session token (JWT) both on the client and server-side when users logout from Citizen OS.

**Comment by ilmartyrk** [comment]
Thank you for noticing this issue. We discussed about possible solutions. We are going to implement token revocation list and also reduce the expiration time for the token to 30-days. As we change the token structure all the current tokens will be invalidated and all users will need to log in again, but this should fix the issue and we won't have any "hanging" sessions.

**Comment by tiblu** [comment]
@ilmartyrk @EgidioRomano 

While this is a significant issue, I would think of it as NOT high priority or critical - that is, we don't need to fix it over the weekend. 

Why I think so:

* We have strict CSP (https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP) which mitigates XSS
* We have validation on `origin` header which mitigates CSRF (https://owasp.org/www-community/attacks/csrf)
* We force the use of HTTPS

So I feel like the ONLY way to actually steal a token is to access a computer where User has NOT logged out.

Let me know if you feel like I underestimate the severity of the issue.

**Comment by anettlinno** [comment]
Triage 53. Sending to development.

**Comment by ilmartyrk** [comment]
Fixed with https://github.com/citizenos/citizenos-api/commit/9bfa481344e03cba533d66305b81210b0d638b42
