### ISSUE TITLE
[SECURITY] Email addresses disclosure in Search API endpoint

### ISSUE THREAD

**Issue by EgidioRomano** [citizenos/citizenos-api#222]
**What is the problem?**
The `/api/search` API endpoint allows unauthenticated attackers to disclose email addresses of Citizen OS users. This information can be used to further attack the application, for instance, through social engineering or login brute-force attacks. To reproduce the issue just use the following Linux commands:

```
$ curl -s "https://api.citizenos.com/api/search?include=public.user&str" | jq
{
  "status": {
    "code": 20000
  },
  "data": {
    "results": {
      "public": {
        "users": {
          "count": 8,
          "rows": [
            {
              "id": "726bd7c0-e670-4179-946e-04fa7648625c",
              "name": "Agustina Iskandar Crombach",
              "company": "Citizen OS",
              "email": "agustina@citizenos.com",
              "imageUrl": "https://lh3.googleusercontent.com/a-/AAuE7mBNJ2GqnDiaGR67iyUMk3ExTYaIUztPWFeM3SSw"
            },
            {
              "id": "b2cc9e86-295c-4850-a667-8c6cb5a44865",
              "name": "Faransina Olivia Rumere",
              "company": null,
              "email": "***@***",
              "imageUrl": "https://graph.facebook.com/2403780509653241/picture?type=large"
            },
            {
              "id": "4db9210b-2c29-4631-aa9a-a398150ee078",
              "name": "Piret Talur",
              "company": null,
              "email": "***@gmail.com",
              "imageUrl": null
            },
            {
              "id": "7292fb45-3e41-42bd-abce-883b9d50c1fd",
              "name": "Sara",
              "company": "Citizen OS",
              "email": "sara@citizenos.com",
              "imageUrl": "https://citizenos-prod.s3.eu-west-1.amazonaws.com/users/25316d6d-087f-4099-a811-2893a7bb529b.png"
            },
            {
              "id": "2da4cdbd-c522-400b-9f83-b77ee963a347",
              "name": "Herta Karjus",
              "company": null,
              "email": "herta.karjus@***",
              "imageUrl": null
            },
            {
              "id": "016f21b7-1540-4ddc-b0bc-583526b1c813",
              "name": "Leony Chrisanti",
              "company": null,
              "email": "***@gmail.com",
              "imageUrl": null
            },
            {
              "id": "b616ca69-3e9b-4678-a143-79b641896de1",
              "name": "Anett Linno",
              "company": "Citizen OS",
              "email": "anett@citizenos.com",
              "imageUrl": "https://lh4.googleusercontent.com/-ek92OXiNUtE/AAAAAAAAAAI/AAAAAAAAAAc/1G7cfh7xhUM/photo.jpg"
            },
            {
              "id": "4c7363e7-0c22-4984-b6f7-c6111a27a5eb",
              "name": "Ilmar",
              "company": null,
              "email": "ilmar@citizenos.com",
              "imageUrl": "https://citizenos-prod.s3.eu-west-1.amazonaws.com/users/238b7851-12ef-4cf4-ba2d-9ac931c200ac.PNG"
            }
          ]
        }
      }
    }
  }
}
```

**Possible solution.**
It is suggested not to disclose email addresses of Citizen OS users within API responses, as this should be considered sensitive information.

**Comment by tiblu** [comment]
@EgidioRomano 

First of all, thanks for having a thorough look at our apps security. I love the reports - they are not hypotetical, but contain proof. Thank you!

When it comes to this issue, I THINK this is by design - User has an OPT-IN option in the profile to allow the information to be public.

![image](https://user-images.githubusercontent.com/7405383/142645182-dd524353-363f-414d-b7c8-1b9864c50275.png)


@ilmartyrk 

* Can you confirm this is true?
* When it comes to actually publishing e-mail, do we really need it? We MAY want to allow e-mail search to return the name, BUT NOT the actual e-mail in the response? To invite User to any context, we only need `userId`?

**Comment by ilmartyrk** [comment]
@tiblu @EgidioRomano this is true that user has to opt-in before appearing in these results. As this endpoints current use-case is for finding users to invite them to groups or topics I was thinking of creating an extra search endpoint that would use loginCheck middleware. Also thought to add minimum character length and result limit so it would make phishing e-mails more difficult.

**Comment by tiblu** [comment]
@ilmartyrk 

I like the ideas:

* It makes sense to have a higher character limit for search. I propose 5. This DOES leave an annoying case where short e-mails/usernames (`a@a.com`) are hard to find, but I'd consider it acceptable.
* It makes sense to have result limit. I'd set it to 5, max 10.

**Comment by EgidioRomano** [comment]
@tiblu, like you said: "To invite User to any context, we only need userId?". I don't know about any context, but in this case I think the `userId` should be enough to invite the user, don't need to disclose the email address too (IMHO).

**Comment by tiblu** [comment]
> @tiblu, like you said: "To invite User to any context, we only need userId?". I don't know about any context, but in this case I think the `userId` should be enough to invite the user, don't need to disclose the email address too (IMHO).

By "any context" I mean Group, Topic. That is - invite a User to Group or a Topic.

**Comment by EgidioRomano** [comment]
Well, in this case I would suggest not to disclose the email address in "any context", do you really need it somewhere? Unless the user explicitly opt-in for email disclosure, their addresses should be treated as "sensitive data".

Furthermore, I'd like you to remember the `/api/search` API endpoint can be accessed by **unauthenticated attackers**!

**Comment by anettlinno** [comment]
Triage 53. Sending to development.

**Comment by ilmartyrk** [comment]
Removed users from general search and created a separate endpoint that requires  5 characters (from start) min. also returns max 5 rows

https://github.com/citizenos/citizenos-api/commit/2b7eb0799f8d8a0c397ab806feea1d48e23a90e4
