### ISSUE TITLE
Update PostgreSQL version

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#224]
Heroku is warning us to update PostgreSQL version
PostgreSQL 10 reaches End of Life on 2022-Nov-10. Due to security and operational concerns, Heroku cannot run unsupported software as a service. Therefore, the following database will need to be updated before 2022-Nov-10

**Comment by anettlinno** [comment]
Triage 59. Updates are needed to be done. 
Approx. update time 2 days (if we are lucky then 10 minutes). Sending it to To do.

**Comment by ilmartyrk** [comment]
Heroku db update article https://devcenter.heroku.com/articles/upgrading-heroku-postgres-databases
Tasklist: 
- [ ] Update local database
- [ ] Run tests and check if anything fails
- [ ] Check manually main flows
- [ ] Update test app database
- [ ] Update live app database

**Comment by tiblu** [comment]
### Upgrade process

* Provisioning a follower database:
    * `heroku addons:create heroku-postgresql:standard-0 --follow HEROKU_POSTGRESQL_SILVER_URL --app citizenos-citizenos-api-prod`
    * `heroku pg:wait`
 * Verify that follower is created and has caught up
    * `heroku pg:info --app citizenos-citizenos-api-prod`

**Comment by tiblu** [comment]
Done. Upgraded to 13.5.
