### ISSUE TITLE
Separate contact e-mail and login e-mail

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#237]
We currently use the same e-mail address for login and sending e-mails. There could be possibly two e-mail addresses. one for login and other for contacting. This would allow users to have one address for all their notifications, but at the same time use different e-mails for logging in.

**Comment by loorm** [comment]
As a user, why would I want this?

**Comment by anettlinno** [comment]
Triage 65. Very complicated to implement and probably difficult to understand for users. 
Closing this issue.
