### ISSUE TITLE
BUG: Topic invite email: wonky footer layout + translation

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-api#239]
**What is the problem?**
1) Email footer design has moved off-center
2) Email footer displays an untranslated string, though translations are at 100% coverage.

<img width="779" alt="Screenshot 2022-04-07 at 13 47 41" src="https://user-images.githubusercontent.com/34126353/162182752-43b61c66-8419-4d04-9632-fae46525770d.png">

**Why is this a problem?**
Looks raw and unprofessional :)

**Comment by anettlinno** [comment]
Triage 65. @oksks @loorm we were discussing where the "empowered by" came from and couldn´t figure it out. Do you know why we say we empower our own product? :) Maybe we misunderstand the meaning. Thank you in advance for the explanation! :))

**Comment by oksks** [comment]
@anettlinno it's an excellent question, I had the same one several years ago - I remember asking @loorm about it as Mikk couldn't explain this either, but unfortunately my memory betrays me and I no longer remember the explanation.

@loorm?

**Comment by anettlinno** [comment]
Triage 66. As we don´t have any good reason or argument why to keep the "Empowered by", let´s remove it from footer and leave only Citizen OS logo. Needs to review, fix and test all emails. Est. time is 30 minutes.
