### ISSUE TITLE
Public groups

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#241]
We need to create public groups feature. We have it on out Big picture board - https://github.com/orgs/citizenos/projects/1#card-14133727
Initial idea is to create a MVP version and then alter it depending on user feedback and needs
Link to MVP description - https://app.citizenos.com/en/topics/0332bb20-49e7-4ea3-8823-9803612bb04b

**Comment by anettlinno** [comment]
Triage 65. @kevin we would need design for public groups please (platform landing page). Please find MVP description here: https://app.citizenos.com/en/topics/0332bb20-49e7-4ea3-8823-9803612bb04b?argumentsPage=1). 

Start developing PVM version of Public Groups. Est. dev. time 2 weeks. Before launching needs user testing. 
Sending to development.

**Comment by kevincrepin** [comment]
Added one prototype here you can create, view and join a public group: https://www.figma.com/proto/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?page-id=3518%3A40968&node-id=3518%3A40969&viewport=478%2C342%2C0.25&scaling=min-zoom&starting-point-node-id=3518%3A40969

I didn't work out the dashboard screens because I think we'll take over the existing private groups designs, right?

Also added mobile references for the new types of pages: https://www.figma.com/file/KWTHiHwLZJ3ZFpNJfoVRXX/Platform-1.0?node-id=3524%3A42161

**Comment by ilmartyrk** [comment]
@kevincrepin I would also like to ask a front-page updated so that public groups or at least reference to public groups page is visible together with public topics

**Comment by ssin1901** [comment]
@ilmartyrk why can’t I see my role or yours (admin/participant) in the public group?

**Comment by ssin1901** [comment]
@ilmartyrk seems to be an issue with the way this is being displayed on screen resolutions below 1024 (IPad OS)
 
![Screenshot 2022-11-01 at 21 52 14](https://user-images.githubusercontent.com/72747107/199326259-52f41282-7f08-44f3-bb36-1dd180232d8e.png)

**Comment by ssin1901** [comment]
@ilmartyrk user with read only rights cannot change the topic text but can remove the public group picture 

![Picture removed](https://user-images.githubusercontent.com/72747107/199328457-ac335dae-6458-4fd7-86be-a46a9f869e77.png)

**Comment by ssin1901** [comment]
@ilmartyrk if I am a participant (screenshot 1) then why can I add topics to the public group (screenshot 2)?

![Screenshot 2022-11-01 at 22 05 05](https://user-images.githubusercontent.com/72747107/199330565-8a705590-613c-4e8f-a30a-2998769549a4.png)

![Screenshot 2022-11-01 at 22 05 05](https://user-images.githubusercontent.com/72747107/199330614-1fb543b9-7cf4-4eca-91ef-fc1445a7adfc.png)

**Comment by ssin1901** [comment]
Also couple of errors here

![Screenshot 2022-11-01 at 23 31 57](https://user-images.githubusercontent.com/72747107/199345862-bf13e3b6-c2fb-4335-8e9a-4a62086d5e5b.png)

![Picture removed](https://user-images.githubusercontent.com/72747107/199345877-a8bf381c-9d14-4968-9f50-c0f9491d43b6.png)

**Comment by ilmartyrk** [comment]
@ssin1901 I believe I've fixed all the issues now

**Comment by ssin1901** [comment]
@ilmartyrk in the test environment,

if you click on Create a new topic (screenshot below)

<img width="1439" alt="Screenshot 2022-11-13 at 17 52 05" src="https://user-images.githubusercontent.com/72747107/201531018-0bc17819-c64b-4c40-8e48-492c55013c9c.png">

You get the registration/login modal but if you click the x/close button (screenshot below) 
<img width="1440" alt="Screenshot 2022-11-13 at 17 52 15" src="https://user-images.githubusercontent.com/72747107/201531097-a799c06d-ebf5-4c4c-9fd4-06e8feece272.png">

You get this modal which **cannot be closed with the x button** and basically stops you from interacting with the site without refreshing the page
<img width="1439" alt="Screenshot 2022-11-13 at 17 52 26" src="https://user-images.githubusercontent.com/72747107/201531154-51c9e702-4cc4-42c7-9f5a-e30900cadfbb.png">

**Comment by ssin1901** [comment]
@ilmartyrk when I added an image that was only 224 kb I got this error message 
<img width="1438" alt="Screenshot 2022-11-27 at 20 59 59" src="https://user-images.githubusercontent.com/72747107/204154501-e0f43c0d-1c89-4558-904f-b25a8506c72a.png">

Whereas when I create a public group without an image that size everything works alright

**Comment by ssin1901** [comment]
@ilmartyrk when you access My Groups (see screenshot below)
<img width="1440" alt="Screenshot 2022-11-27 at 21 02 15" src="https://user-images.githubusercontent.com/72747107/204154622-61f14063-c7ee-4ddb-8fa1-f7a7e547af70.png">

You can find all the public groups 
<img width="1440" alt="Screenshot 2022-11-27 at 21 03 41" src="https://user-images.githubusercontent.com/72747107/204154663-e79b96dd-3006-4039-8c8d-ac2f9534ef36.png">

But you have no way of knowing whether they are public or private and this leaves a lot of scope for error on the users part
<img width="1440" alt="Screenshot 2022-11-27 at 21 03 36" src="https://user-images.githubusercontent.com/72747107/204154684-f6d2caea-0b5c-4075-835c-68d13ae42867.png">

**Comment by ssin1901** [comment]
Topic created and added to the Public group is still Private by default (See screenshots 1 and 2). This may be confusing to some users
<img width="1440" alt="Screenshot 2022-11-27 at 23 00 00" src="https://user-images.githubusercontent.com/72747107/204159515-7cfc13cc-09cc-4f24-8503-0ccdae2ed81a.png">

<img width="1440" alt="Screenshot 2022-11-27 at 23 00 23" src="https://user-images.githubusercontent.com/72747107/204159516-46014829-0fb6-4a26-83b5-14a2d7c2a024.png">

**Comment by ssin1901** [comment]
Despite the group being "public", I cannot leave the group if I am the last admin member (see screenshot)
<img width="1440" alt="Screenshot 2022-11-27 at 23 02 24" src="https://user-images.githubusercontent.com/72747107/204159598-f4e5f29a-b396-46b7-9d47-57a775a36e66.png">

**Comment by ilmartyrk** [comment]
@Sara

**Comment by ssin1901** [comment]
@ilmartyrk I had an issue with generating a link. When I clicked on copy link I got an error (see screenshot)

<img width="1168" alt="Screenshot 2022-11-28 at 14 12 02" src="https://user-images.githubusercontent.com/72747107/204337030-9f9d4042-4668-425f-b0cc-4c282a75d647.png">

**Comment by ssin1901** [comment]
A second error from the same process

<img width="1171" alt="Screenshot 2022-11-28 at 14 13 40" src="https://user-images.githubusercontent.com/72747107/204337207-e0f84359-03b7-4bf9-ae0f-57e310d8a0c3.png">

**Comment by ssin1901** [comment]
@ilmartyrk 

When you go to a particular public topic (for example Group for Alex)>Settings>Add Topic you can Create a Topic that immediately gets added to the public group. Yet you also have to click Create Group which doesn't do anything.

<img width="1440" alt="Screenshot 2022-11-28 at 23 23 24" src="https://user-images.githubusercontent.com/72747107/204384094-ace44a1e-788d-4a5d-836e-3b0d089fd5cf.png">

**Comment by anettlinno** [comment]
Triage 75. 

1. @kevincrepin Public and private groups are unclear now (the lock icon is rather confusing) and we would like to have better understandable solution. Maybe writing "public group" and "private group"
3. We only allow adding public topics into public groups. New issue will be created on that. 
5. Rename the button "Save topic" to "Save"

Est. dev. time 10 minutes

**Comment by ilmartyrk** [comment]
2. Added update to front-end so UI does not allow adding private topics to public groups and also hides private/public toggle from topic settings if topic is added to public group, still needs API side update too
3. Changed button name

**Comment by anettlinno** [comment]
Triage 76. My groups view will be the same as Public groups. 

@kevincrepin we would still need the design for the groups to better understand if the group is private or public (screenshot)

Est.dev time 3 hours.

**Comment by anettlinno** [comment]
Triage 78. Closing issue.
