### ISSUE TITLE
E-mails: Configurable logos - update e-mail layout so that Citizen OS logo is always present even when custom logo is used

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#26]
**Overview** 

One can configure their own logo for the e-mails (https://github.com/citizenos/citizenos-api/blob/master/config/emails/README.md).

**Problem**

There is no Citizen OS branding in the e-mail, if a custom logo is used.
Why? Help spread spread the word of Citizen OS OSS existence.

**TODO**

- [x] Implement the e-mail layout as per https://projects.invisionapp.com/d/main#/console/9829159/318396373/preview

![image](https://user-images.githubusercontent.com/7405383/47804772-53e49400-dd3e-11e8-87ab-8f616089890a.png)

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-api/commit/29e1c6a5f51d49b66171ffa1b0cd0042048ee4be
