### ISSUE TITLE
Only allow public topics inside public groups

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#273]
Currently public groups can have private topics, that are only visible for members of the group. As it makes sense for public groups to have public topics, we should only display public topics in search list and if creating a new topic it will also by default be public. Also update topic flow should not allow changing status to private if topic is in public group.

**Comment by ilmartyrk** [comment]
Implemented in the front-end side, still need API update

**Comment by anettlinno** [comment]
Triage 76. 
Est. dev. time 3 hours. Sending it To Do.

**Comment by BeccaMelhuish** [comment]
@ssin1901 what do you say if we put this into QA, for you to test the current situation post-redesign, and see if this one still needs to stay open? Will put it there for now :)

**Comment by ssin1901** [comment]
@ilmartyrk @BeccaMelhuish little confused about this issue.

Currently in the Test Environment, Group Admins can add Private Topics to their Public Groups via Add Existing Topic. They can also add Private Groups to their Public Topics.

If they create a Topic within the group it is by default set to Private but with the Public Group added. 

Essentially, Private Topics are allowed in Private Groups. To be honest, not quite sure why this flow needs to be updated as everyone who has access to the Group, has access to the Topic (regardless of status). 

Is the issue that users discover that their private topics cannot be removed without removing all the group members?

**Comment by BeccaMelhuish** [comment]
@ssin1901 as @ilmartyrk noted in [this issue](https://github.com/citizenos/citizenos-fe/issues/752#issuecomment-1931880586), this is quite a can of worms, so I've made a new issue for DUX to hopefully review what would be the best UX in terms of mixing public and private, or how to avoid it smoothly: #1659 

Can I just check this bit though: _"If they create a Topic within the group it is by default set to Private but with the Public Group added."_ In #865 we decided that if a topic is created from within a group it would have its visibility settings 'locked' to match those of the group. Does this mean this isn't working as it should, and that issue should therefore be re-opened? 

To check also, am I right in understanding that there is currently a way that private topics that have already had participation (i.e. they are not newly created) can be added to public groups? As if so, that's quite a privacy issue. 

What did you mean about this part: _"Is the issue that users discover that their private topics cannot be removed without removing all the group members?"_ I've not got my head around it but it seems potentially important, though may be a separate issue?

**Comment by ssin1901** [comment]
@BeccaMelhuish 
Here is a screen recording of Topic created from Group. It remains Private even though the group it was created for is Public. 

https://github.com/user-attachments/assets/b3bf8cbe-84cd-4ec5-a395-53badff38a1c

**Comment by BeccaMelhuish** [comment]
OK thank you @ssin1901! Will make a separate issue for that, seems quite high priority but let's discuss there :)

**Comment by BeccaMelhuish** [comment]
Will close this one now as we have it covered here: https://github.com/citizenos/citizenos-fe/issues/1659
