### ISSUE TITLE
API: GET /api/activities - DB out of memory errors on high load

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#28]
**Reproduce**

```
ab -n 1000 -c 10 "http://citizenos-citizenos-api-prod.herokuapp.com/api/activities"
```

**Result**

```
05 Sep 2018 11:38:47.607226 <190>1 2018-09-05T08:38:46.917613+00:00 host app web.2 - [31m[2018-09-05T08:38:46.912] [ERROR] production - [39mEndpoint GET "/api/activities" failed miserably. Status: undefined Stack: SequelizeDatabaseError: out of memory
05 Sep 2018 11:38:47.60781 <190>1 2018-09-05T08:38:46.903537+00:00 host app web.2 - severity: 'ERROR',
05 Sep 2018 11:38:47.60681 <190>1 2018-09-05T08:38:46.903458+00:00 host app web.2 - severity: 'ERROR',
05 Sep 2018 11:38:47.476123 <132>1 2018-09-05T08:38:46+00:00 host app postgres.2097 - [DATABASE] [135-1] sql_error_code = 53200 ERROR: out of memory
05 Sep 2018 11:38:47.476122 <132>1 2018-09-05T08:38:46+00:00 host app postgres.2088 - [DATABASE] [75-1] sql_error_code = 53200 ERROR: out of memory
05 Sep 2018 11:38:47.273123 <132>1 2018-09-05T08:38:46+00:00 host app postgres.2112 - [DATABASE] [106-1] sql_error_code = 53200 ERROR: out of memor
```

**Reading**

* https://devcenter.heroku.com/articles/postgres-logs-errors#out-of-memory-errors
* https://devcenter.heroku.com/articles/heroku-postgres-metrics-logs

**Comment by ilmartyrk** [comment]
Read a lot of Postgres documentation about functions, indexing, also looked around for articles. Probably the simplest to understand and try out was this:
https://statsbot.co/blog/postgresql-query-optimization/
Took apart all the main queries and run them separately to find the slowest and found out that they were quite ok. So after that rewrote query that built the returning data into a function and that helped to bring down the cost, but performance got really slow. Finally concentrated on query order. So to first narrow down ID-s to return and after that get all data that is only related to these.
Final results without adding any new indexes or altering DB structure (Run on local DB with about 30000 rows in Activities table, created by re-running all the tests over and over):
**Query cost from**: _30821841.70_ -> _207202.78_
**Execution time**  _2247.545_ -> _607.797 ms_
**Memory usage under load test described in this issue** ~_180MB_ -> ~_40MB_
**Execution times under load test:** 
- min 3815ms -> 832ms 
- median 8062ms ->2281ms  
- max 12332ms ->3859ms
