### ISSUE TITLE
Max characters for invite email - UX issue

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-api#287]
@ssin1901 notes here in the HC doc that it seems a user can add as much text to their email invitation as they like, but only 999 characters will actually be sent. 

So for better UX, they should be able to add only 1000, and then be told they have reached the maximum and not be able to add any more. 

![image](https://user-images.githubusercontent.com/61320526/236820865-51a43965-b374-46d2-9c24-9bfad24007dd.png)

**Comment by anettlinno** [comment]
Yes, there should be information about the character limit, I agree. I just checked that there isn´t any in the redesign either: 

<img width="248" alt="Character limit" src="https://github.com/citizenos/citizenos-api/assets/45175679/7fd13a32-b98b-465e-a26f-e3b1f6535c07">

@ilmartyrk please double-check if the character limit is 999 (Y)
@kevin please add character limit in Figma designs as well (Y)

**Comment by kevincrepin** [comment]
Added! You can find the modal here: https://www.figma.com/file/gOJ4i00538e0qaP6IKIPVE/Platform-2.0-UI?type=design&node-id=524%3A62243&t=6uD5Bsxishw4ipqq-1

**Comment by ilmartyrk** [comment]
This has been added long time ago, closing issue
