### ISSUE TITLE
Odd black bar showing on homepage on mobile

### ISSUE THREAD

**Issue by BeccaMelhuish** [citizenos/citizenos-api#288]
On my Android phone when viewing the homepage, there is this odd black bar between the public topics heading and the public topics themselves. Makes it hard to understand the relation between the heading and the topic, as seems like an "end of section" bar. And is out of keeping with the rest of the design too, like there is a "gap" in the design. 

![image](https://user-images.githubusercontent.com/61320526/236863338-51b723c4-1a4f-49ac-becd-2063e8a4fe3c.png)

@ilmartyrk @ssin1901

**Comment by anettlinno** [comment]
Triage 86. Quick fix, 10 min. Sending it TO DO.
