### ISSUE TITLE
Error message is hard to understand

### ISSUE THREAD

**Issue by anettlinno** [citizenos/citizenos-api#290]
**What is the problem?**
I wanted to invite User to Public Group and received following error message:
<img width="656" alt="Sending invite failed" src="https://github.com/citizenos/citizenos-api/assets/45175679/96778fb4-f257-4a3d-bdb1-0c7ed5cad827">

**Why is this a problem?**
Please let´s change the "duplicate action or invalid data provided" into more mundane copy. Like "Sending invites failed: **this user is already in this group or entered email address is incorrect**"

**Possible solution.**
Please let´s find better copy.

**Comment by anettlinno** [comment]
Triage 85. @oksks please help us to find better copy for that. Thanks you in advance! :)
Sending to To Do.

**Comment by oksks** [comment]
How about this:
>Sending invites failed: user already in the group, or incorrect email address

**Comment by ilmartyrk** [comment]
@oksks @anettlinno as we use the same message for group and topic invites I suggest Sending invites failed: user already a member, or incorrect email address. Is this ok?
