### ISSUE TITLE
BUG: Final BDOC generation is slow resulting in request timeouts

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#30]
**Overview**

For in case of significant amount of signatures the final BDOC generation times out.

```
25 Oct 2017 15:39:22.5101048 <158>1 2017-10-25T12:39:21.942192+00:00 host heroku router - at=error code=H12 desc="Request timeout" method=GET path="/api/topics/78ba564c-9843-4dc1-8e79-dcad2941537c/votes/6f0ef16d-067c-4034-be36-9ab32dcda9f0/downloads/bdocs/final?token=x&accept=application%2Fx-7z-compressed" host=api.citizenos.com request_id=68252540-6ca7-4466-88ea-1c294c9ea8f3 fwd="x" dyno=web.1 connect=0ms service=30000ms status=503 bytes=0 protocol=https
```

**TODO**

- [ ] Speed up the generation, there is a test case to play around - https://github.com/citizenos/citizenos-api/blob/master/test/libs/cosBdoc.js#L164

**Comment by anettlinno** [comment]
Triage 37. Issue occurs only when there are many e-signatures. Needs investigation and probably stress test. 
Approx. investigation time 1h. Sending to To do.

**Comment by anettlinno** [comment]
Triage 76. Haven´t come up lately any more and will close the issue.
