### ISSUE TITLE
My topics list includes draft topics for users with participant permissions

### ISSUE THREAD

**Issue by ilmartyrk** [citizenos/citizenos-api#325]
Draft topics should only be accessible for users with editor or admin permissions.

**Comment by ssin1901** [comment]
@ilmartyrk to clarify – this would show up in My Topics if draft topic was added to a Group? I understood that a user cannot invite others to a draft topic.

**Comment by ssin1901** [comment]
Will create a new issue if needed but haven't had the issue of Draft topics where I am a participant appearing under My Topics. Closing the issue.
