### ISSUE TITLE
Tech dept: Remove `parentId` from Group model

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#33]
**Overview**

`Group` model has `parentId` in the model definition which is not used - https://github.com/citizenos/citizenos-api/blob/master/db/models/Group.js#L32
This is probably a copy-paste mishap.

**TODO**

- [ ] Remove `parentId` from `Group` model - https://github.com/citizenos/citizenos-api/blob/master/db/models/Group.js#L32

**Comment by anettlinno** [comment]
Triage 37. Decided not to remove parent ID from Group model. Closing the issue.
