### ISSUE TITLE
Emails - Mailgun delivery is sometimes way too slow

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#38]
**Overview**

Sometimes Mailgun delivers e-mails too slowly. 
It took 8 min from accepting to delivery for an email below:
```
10/19/16 08:35 AM Delivered: no-reply@citizenos.com → xxxxx@gmail.com 'Rahvaalgatus.ee kasutaja John Smith kutsub Sind kooslooma arutelu/algatust' 
 10/19/16 08:27 AM Accepted: no-reply@citizenos.com → xxxxx@gmail.com 'Rahvaalgatus.ee kasutaja John Smith kutsub Sind kooslooma arutelu/algatust'
```
It is way too long for password reset and signup emails.

**Reading**

* https://help.mailgun.com/hc/en-us/articles/203306890-I-just-submitted-a-lot-of-messages-Why-is-delivery-happening-so-slowly-
* http://stackoverflow.com/questions/26012969/mailgun-messages-accepted-but-taking-long-time-to-be-delivered-or-not-being

**TODO**

- [ ] Pinpoint and fix the delivery lag.

**Comment by anettlinno** [comment]
Triage 37. Couldn´t replicate in Triage. As this issue is old, it´s probably solved already. Closing the issue.
