### ISSUE TITLE
Public note for Topic

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#4]
Support public note for Topic so that people can insert extra public info.

Tech:
* 1 note per Topic.
* Free text

Related tasks:
* https://github.com/rahvaalgatus/rahvaalgatus/issues/54

**Comment by tiblu** [comment]
rahvaalgatus/rahvaalgatus#54

**Comment by anettlinno** [comment]
Triage 56. Interesting feature. Needs user stories. Few that we were discussing:
- Topic initiator wants to share her contacts with the aim that journalists could contact her if they have further questions;
- Topic initiator can add all related organizations;
- Any further information about the topic. 

Sending back to In preparation for further discussion.

**Comment by loorm** [comment]
One function for such a field, that we have talked about several years ago, is "Topic procedure" or something like it. Perhaps it's more relevant to groups, but in any case, this would be a space, where the initiator or moderators can write down the rules and principles of discussion. Deadlines, what is considered appropriate and inappropriate etc. So topic content would actually be for content. And this extra field would be for process related stuff.
