### ISSUE TITLE
Mobiil-ID auth - SPChallenge validation

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#40]
**Overview**

When executing authentication, it's a best practice to generate a `SPChallenge` and validate it on successful authentication - http://sk-eid.github.io/dds-documentation/api/api_docs/#mobileauthenticate.

Related API routes:

* `POST /api/auth/mobile/init`
* `GET /api/auth/mobile/status`

**TODO**

- [ ] Implement `SPChallenge` generation and validation for MID authentication
- [ ] Review Mobiil-ID signing process, see if there is similar concept to `SPChallenge`. IF there is, make sure it's used.

**Comment by tiblu** [comment]
Moved to project, first off - verify what is the problem that `SPChallenge` solves - that is, how critical this really is?

**Comment by ilmartyrk** [comment]
In Mobile-ID REST API this field is called hash, but behaviour and result is the same as in digidoc service

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.
