### ISSUE TITLE
E-mails: Drop usage of campaign-mailgun, use SMTP instead

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#47]
**Overview**

`campaign-mailgun` uses Mailgun API, but Mailgun can be used over SMTP so it provides no extra value.
Rather, it provides extra problems - the Campaign switches on e-mail tracking which rewrites links in the e-mails. 

**TODO**

- [ ] Drop usage of `campaign-mailgun`
- [ ] Configure servers to use campaign over SMTP

**Comment by ilmartyrk** [comment]
possible library to use https://github.com/mailgun/mailgun.js

**Comment by anettlinno** [comment]
Triage 37. Current campaign-mailgun is outdated and needs to be updated to what Ilmar proposed above. 
Approx. dev. time 1 day. Sending to development.

**Comment by ilmartyrk** [comment]
Update campaign and related packages, created pull requests. All in all it is really good library. Fixed all related packages too. Hopefully pull requests are accepted and we can revert back to getting packages from npm. But if that will not happen in recent month or so will create our own release or merge this directly to our code.

**Comment by ilmartyrk** [comment]
Added test coverage for all our current e-mails but these would need to be more thorough, created a new issue for that as it is not with so high priority https://github.com/citizenos/citizenos-api/issues/229
