### ISSUE TITLE
API: Topic attachment's original name becomes alphabet soup when downloaded

### ISSUE THREAD

**Issue by oksks** [citizenos/citizenos-api#61]
**Current situation:**
Downloaded topic attachment loses its original name, turns from descriptive to random characters and numbers.

**Expected behavior:**
Downloaded topic attachment retains its original file name. 

**Reproduce:**
1) Give some file a proper name with words and all (_Team meeting memo_November.docx_ in my case)
2) Upload the file as an attachment to a topic
3) Download the attached file from within the topic. Downloaded file's name becomes a collection of random characters (_057ada2b-56c4-4798-8d0a-7371245eb3a5.docx_ in my case)

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-fe/issues/117
