### ISSUE TITLE
API: Activities - triple "upvote" events in activity feed

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#64]
**Overview**

Activity fees shows 1 upvote 3 times.

**Reproduce**

* Go to public Topic - https://app.citizenos.com/en/topics/3f3c38af-6e3b-471a-9d95-2030a632bcf6
* Log in
* Up/downvote an argument

**Result**

* Activity feed contains several events per 1 up/downvote

**TODO**

- [ ] Fix activities API to store and return upvote event once

![image](https://user-images.githubusercontent.com/7405383/49740883-e6614700-fc9d-11e8-9d47-1f3e60eb48ad.png)

**Comment by ilmartyrk** [comment]
Fixed by https://github.com/citizenos/citizenos-api/commit/673529d9415e758c64b28fdfdf7315636675bd9a
