### ISSUE TITLE
Voting - creates multiple VoteList lines and is not idempotent

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#69]
**Overview**

Voting in general & mobiil-ID voting - `GET /api/users/:userId/topics/:topicId/votes/:voteId/status`, which is used for polling signature state, creates multiple VoteList lines and is not idempotent which is a bad design.

There are several things questionable about this voting endpoints:

* By the REST standard `GET` should be _safe_ (https://en.wikipedia.org/wiki/Hypertext_Transfer_Protocol#Safe_methods) and _idempotent_  (https://en.wikipedia.org/wiki/Idempotence) BUT the `GET /status` is neither. It adds User entry on successful signing and also multiple VoteList lines if called several times AFTER success.  **NOTE:** It does NOT affect the vote results.
* `/status` used for polling the Mobiil-ID signing status. Why not do the polling server-to-server in the background which would enable the person to close the window after initiating the signing? That would make the calling `/status` optional. Right now it's required to register a vote, if something happens and the polling fails, the vote is never registered.
* I used to create multiple VoteList lines to resolve disputes over "how many times I actually voted" and "I did not vote like this" cases. But after we created Activity Feed, those cases can be solved by looking at the feed.

**Comment by tiblu** [comment]
**TODO: Sort this info**

> UPSERTi poleks ju ka vaja. Noop mutatsiooni vaatenurgast.
> Üldsegi, miks on status'e kutsumine vajalik, et andmebaasi rida tekitada?
> See peaks toimuma selja taga ja staatuse vaatamine valikuline. Miks ei võiks inimene Mob-Id PINi sisse > loopida ja akna kinni panna? (edited)

**Comment by ilmartyrk** [comment]
#Triage 11:
Investigate if activity feed contains enough data to retain user voting history.

**Comment by loorm** [comment]
Related to #100

**Comment by KatiVellak** [comment]
Legally reviewed, no impact.

**Comment by ilmartyrk** [comment]
FIXED by https://github.com/citizenos/citizenos-api/commit/076f7d2145c338edea233a0f7511d43995ea05f2
