### ISSUE TITLE
Activity feed - filter

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#7]
Enable filtering by:
* activity type (vote etc)
* topicId

The need - for example rahvaalgatus.ee wants User to see when and if he/she has voted.

Related tasks:
* https://github.com/rahvaalgatus/rahvaalgatus/issues/17

**Comment by ilmartyrk** [comment]
General activity feed already had an filter option, but now there is option to also filter `VoteList` objects, to return only voting activities. `/api/topics/:topicId/activities` and `/api/users/:userId/topics/:topicId/activities` endpoints already existed, but now they also support filter query attribute. Currently allowed filters are `['Topic', 'Group', 'TopicComment', 'Vote', 'User', 'VoteList']`

**Comment by tiblu** [comment]
@moll Does the update help you solve https://github.com/rahvaalgatus/rahvaalgatus/issues/17?

**Comment by moll** [comment]
Possibly. Although I suspect it'd be equally easy for us to query that information directly from the database during an initiative's vote period. We're planning to purge signatures after an initiative has finished and will likely depend only on a related "subscribe to updates" feature to emphasize initiatives a person's involved in.

**Comment by moll** [comment]
That's at least the approach I'm pushing for in https://github.com/rahvaalgatus/rahvaalgatus/issues/115#issuecomment-447681577. :)
