### ISSUE TITLE
Google+ APIs shutting down (Affected endpoint "plus.people.get")

### ISSUE THREAD

**Issue by moll** [citizenos/citizenos-api#72]
As you may know, Google is shutting down Google+ and some APIs with it (https://developers.google.com/+/api-shutdown). An email of warning Google sent, it seems CitizenOS is using `plus.people.get`. Is that true?

**Comment by tiblu** [comment]
Yes, that is true. We use https://github.com/jaredhanson/passport-google-oauth2 (0.1.6) which does this request.

There is an open issue and a PR to fix it, once it's fixed, we'll upgrade the library.

Issue: https://github.com/jaredhanson/passport-google-oauth2/issues/50
PR: https://github.com/jaredhanson/passport-google-oauth2/pull/51

**Comment by tiblu** [comment]
Seems like that the issue can possibly be addressed with configuration change - https://github.com/OpenUserJS/OpenUserJS.org/issues/1526

**Comment by ilmartyrk** [comment]
Update by https://github.com/citizenos/citizenos-api/commit/cc9f70470281a5ab42547aeb621b8cd809fd05aa
