### ISSUE TITLE
API: PATCH /api/users/self/topics/:topicId - if Parliament e-mail sending fails, Topic status is still updated

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#77]
**Overview**

When you send a Topic to Parliament using `PATCH /api/users/self/topics/:topicId`, Citizen OS sends e-mails to Parliament. If the e-mail sending fails, the Topic status is still updated thus leaving the User wrong impression that the proposal was successfully sent to Parliament while they actually haven't received it.

**Possible solutions**

1. Send the e-mails inside DB transaction, so that if they fail, DB transaction is rolled back thus Topic status remains the same and User knows that something failed.
2. Combine solution 1 with a more robust e-mail sending solution that includes retries. This is quite a bit of work as you need to distinguish what is a temporary failure, what is a permanent failure. It must be a separate batch protsess as if the API crashes, the queue gets wiped BUT separate batch process adds more complexity to deployment. In conclusion this solution needs a lot of thinking.

**TODO:**

- [ ] Implement solution 1: Send the e-mails inside DB transaction, so that if they fail, DB transaction is rolled back thus Topic status remains the same and User knows that something failed.

**Comment by anettlinno** [comment]
Triage 58. Needs investigation, inv. time 30 minutes.

**Comment by ilmartyrk** [comment]
As this feature was RAA centered, decided to remove it as we would need a total redesign anyway.
