### ISSUE TITLE
README: Improve  contribution section to include non-code related contributions

### ISSUE THREAD

**Issue by tiblu** [citizenos/citizenos-api#98]
**Overview**

Citizen OS aims to be more than just an app, we aim to be a community beyond coding.
There are many other areas we are interested in outside coding, thus  there are many other ways to contribute.

**Related to**

* https://github.com/citizenos/citizenos-fe/issues/176

**TODO**

- [ ] Describe all more ways to contribute in the contributions section.
- [ ] Move contribution section up in the README.md

**Comment by anettlinno** [comment]
Triage 52. We could describe how to contribute wider on community level. Assigning to myself to update the "Get involved" page on our web site: https://citizenos.com/get-involved/ and link this to GitHub README section.
